######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 29 12:45:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h player.h
SOURCES += main.cpp mainwindow.cpp player.cpp
RESOURCES += resource.qrc
